#!/bin/bash

sudo apt update

sudo apt install build-essential clang flex bison g++ gawk \
gcc-multilib g++-multilib gettext git libncurses-dev libssl-dev \
python3-distutils rsync unzip zlib1g-dev file wget


cp config/def_config ./openwrt/.config
cp build/files ./openwrt/ -r

cd connectedhomeip

git submodule update third_party/pigweed \
  third_party/jsoncpp \
  third_party/nlassert \
  third_party/editline \
  third_party/nlunit-test \
  third_party/nlio \
  third_party/perfetto \
  third_party/libwebsockets 

cd ../
cd openwrt
cp feeds.conf.default feeds.conf
echo src-git ezmesh https://github.com/RafaelMicro/EZMesh.git >> feeds.conf
echo src-link chip $PWD/../package/project-chip >> feeds.conf

./scripts/feeds update -a
./scripts/feeds install -a 

make defconfig
