#!/bin/bash

sudo apt update

sudo apt install build-essential clang flex bison g++ gawk \
gcc-multilib g++-multilib gettext git libncurses-dev libssl-dev \
python3-distutils rsync unzip zlib1g-dev file wget


cp config/def_config ./openwrt/.config
cp build/files ./openwrt/ -r

cd openwrt
cp feeds.conf.default feeds.conf
echo src-git ezmesh https://github.com/RafaelMicro/EZMesh.git >> feeds.conf

./scripts/feeds update
./scripts/feeds install

make defconfig
