#!/bin/bash

sudo apt update

sudo apt install -y build-essential clang flex bison g++ gawk \
  gcc-multilib g++-multilib gettext git libncurses-dev libssl-dev \
  python3-distutils rsync unzip zlib1g-dev file wget libglib2.0-dev

git submodule update --init

cp build/files ./openwrt/ -r

cd third_party/connectedhomeip

git submodule init
git submodule update third_party/pigweed \
  third_party/jsoncpp \
  third_party/nlassert \
  third_party/editline \
  third_party/nlunit-test \
  third_party/nlio \
  third_party/perfetto \
  third_party/libwebsockets

cd ../../openwrt
cp feeds.conf.default feeds.conf
echo src-link ezmesh $PWD/../package/RafaelMicro/EZMesh >>feeds.conf
echo src-link chip $PWD/../package/project-chip >>feeds.conf

./scripts/feeds update -a
./scripts/feeds install -a

cp ../config/def_config_mt7688 ./.config
make defconfig
